language: elixir
elixir:
  - 1.8.2
otp_release:
  - 22.0
cache:
  directories:
    - _build
    - deps
jobs:
  include:
    - stage: "Testing"
      name: "Running all the tests"
    - script:
      - mix test
    - stage: "Compile"
      name: "Compile Postit Web App"
    - script:
      - mix edeliver build release --branch=BRANCH --verbose
      - mix edeliver deploy release to production --verbose
      - mix edeliver start production --verbose
      - mix edeliver migrate production up --verbose
    - deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false