    
language: elixir
elixir:
  - 1.8.2
otp_release:
  - 22.0

script:
  - mix edeliver build release --branch=BRANCH --verbose
  - mix edeliver deploy release to production --verbose
  - mix edeliver start production --verbose
  - mix edeliver migrate production up --verbose
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: develop

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false