language: elixir
elixir:
- 1.8.2
otp_release:
- 22.0
cache:
  directories:
  - _build
  - deps
addons:
  ssh_known_hosts: postit.blog

script:
  - mix edeliver build release production

after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
before_install:
- openssl aes-256-cbc -K $encrypted_71b6d6e1e8cf_key -iv $encrypted_71b6d6e1e8cf_iv -in deploy_travis_rsa.enc -out ./deploy_travis_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_travis_rsa
- echo -e "Host $BUILD_SERVER_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_travis_rsa
