env: flex
runtime: custom
instance_class: F1
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
beta_settings:
  cloud_sql_instances: post-it-243617:us-central1:postitdb-beta
