steps:  
# Building image
# Note: You need a shell to resolve environment variables with $$
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [ 
          '-c',
          'docker build -t gcr.io/post-it-243617/postit:$REVISION_ID --build-arg DB_PASSWORD=$$db_password --build-arg  DB_NAME=$$db_name --build-arg DB_SOCKET_DIR=$$db_socket_dir --build-arg DB_USERNAME=$$db_username --build-arg SECRET_KEY_BASE=$$secret_key_base  .'  
        ]
  secretEnv: ['db_password', 'db_name', 'db_socket_dir', 'db_username', 'secret_key_base']  
  

# Push Images       
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/post-it-243617/postit:$REVISION_ID'] 
  
# Deploy to GAE
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
          'set',
          'image',
          'deployment/postit-web',
          'postit-web=gcr.io/post-it-243617/postit:$REVISION_ID'
        ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=postit-cluster'

secrets:
- kmsKeyName: projects/post-it-243617/locations/global/keyRings/vmi-integration-secrets/cryptoKeys/postit-web
  secretEnv:
    db_name: CiQAHWmR6w9yfZ3CWpTJRL+LugIp2a4lJ9S3rg+zj3CDco98RzMSMgC1028qVkuXJkuHzZguc0DIqZjCt6C+bHTBWZ6degDEgMR9PK/CyvmfRlX4Eoob1rlz
    db_password: CiQAHWmR62hlx670Jmb533iFZ2w1p3ZcokQTfEQT0kZcH4mkh4USMgC1028qRtAShxplIezPjZAW+pqpTlUJ6zrGbeS3Rjjna4Zj2VpFy5E94tEn1KVpseiV
    db_socket_dir: CiQAHWmR6yWehUuRNBSPktKDzfTYbA2gpkMQTvg76tPiD3zxwL4SWwC1028qBAwHYjv6J5ZDJNjW+9dfqsdCYtSU/973giL3pipc9C9DBG+PW4f4+dokqeIqC6M9xLOfNVC9fngC8TfC+uu6hRZ3EhzEi+WbBuOD8osGQuiCGK6oHg4=
    db_username: CiQAHWmR63G+OPHaUWxOF62HRN7hK+yNqT0UbU27YGGOrvz6quoSMgC1028q6XrU2ani05rRr+mjaTwXhni1VGi1sqcWrzMDMpSFALMXcr7u3dXAzSaJ9r4f
    secret_key_base: CiQAHWmR674RptPyFJt4tm3ox467gF3Oz49dGVt7IjaT68uwBP8SagC1028qxPgnRg3sOMDRudYntLj61I+SXRYTNmlu0Crkdq2xU5lnhfdRXXMep34g7vG5uWmr68Jlj5RslPqFmMusuOm+0cCB7HVv6G3CqWNYWsPTvyVEFUB5Re+thlwDLKYfZnDh4Wyrd7U=
